version: "3.8"

services:
  api:
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && 
      python manage.py migrate && 
      gunicorn perrysAPI.wsgi:application -c gunicorn.py.ini"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - perrys_database:/var/lib/mysql
    env_file:
      - .env

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./perrysAPI/static:/static
    ports:
      - 80:80
      - 1337:80
    depends_on:
     - api

volumes:
  perrys_database: {}